apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: pythonmlnotebookgpu
  namespace: 2663460aproject
spec:
  replicas: 1
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: pythonMLNotebook
        deploymentconfig: pythonMLNotebookGPU
        group: 2663460a
    spec:
      nodeSelector:
        node-role.ida/gputitan: "true"
        # node-role.ida/gpu2080ti: "true"
      containers:
      - name: notebook-container
        image: joe3012/epsrc23:latest
        resources:
          requests:
            cpu: "2000m"
            memory: "32Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "3000m"
            memory: "32Gi"
            nvidia.com/gpu: 1
        env:
        - name: HOME
        value: "/nfs/home"
        - name: ROS_HOME
          value: "/nfs/home/.ros/"
        - name: UGRWS_DIR
          value: "/nfs/ugrdv/"
        - name: EUFS_MASTER
          value: "/nfs/ugrdv/ros2_ws/src/eufs_sim"
        - name: DATA_COLLECTION_REPO
          value: "/nfs/sim_data_collection"
        - name: SCRIPTS_REPO
          value: "/nfs/cluster-files"
        - name: NOTEBOOK_REPO
          value: "/nfs/vehicle-model"
        command:
          - '/nfs/cluster-files/scripts/start_notebook.bash'
        ports:
          - containerPort: 8888
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /nfs/
            name: nfs-access
      securityContext: {}
      serviceAccount: containerroot
      volumes:
      - name: nfs-access
        persistentVolumeClaim:
          claimName: 2663460avol1claim
